// Données des projets
const PROJETS = [
  {
    "id": 1,
    "slug": "theodora",
    "title": "Theodora Boss Lady",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/bosslady.jpg",
    "description": "Affiche réalisée pour la chanteuse Theodora, représentant pleinement son univers unique. L’identité visuelle mélange un côté girly et doux avec des touches badass, reflétant sa personnalité et son univers musical. Le design intègre des éléments graphiques subtils, évoquant la force et la féminité, tout en restant élégant et impactant.",
    "tags": ["Affiche"],
    "featured": true,
    "outils": ["Photoshop"],
    "category": "Perso"
  },
  {
    "id": 2,
    "slug": "bushi",
    "title": "Bu$hi - Épilogue",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/bushi/EPILOGUE.png",
    "description": "Création de la cover d’album dans le cadre d’un concours pour le rappeur Bu$hi. Ce projet, nommé Épilogue, reprend des éléments visuels emblématiques des précédentes Bushi Tape : crâne, Saturne, volcan, masque d’Obito… Le design vise à faire le lien entre le passé et la conclusion de la série, tout en apportant une esthétique moderne et cohérente avec l’univers du rappeur.",
    "tags": [""],
    "featured": true,
    "media": [
      "images/projects/bushi/CD_fermé.jpg",
      "images/projects/bushi/CD_ouvert.jpg",
      "images/projects/bushi/deezer.jpg",
      "images/projects/bushi/écran_accueil.jpg",
      "images/projects/bushi/vinyle.jpg",
      "https://res.cloudinary.com/djgl3a7kw/video/upload/v1768939101/pr%C3%A9sentation_album_ldoa9r.mp4"
    ],
    "outils": ["Photoshop"],
    "category": "Perso"
  },
  {
    "id": 3,
    "slug": "mmi-d-or",
    "title": "MMI D'OR",
    "type": "Évènement",
    "year": 2025,
    "cover": "images/projects/MMIDOR/affiche_foncée.png",
    "description": "Direction artistique complète pour l’événement universitaire MMI d’Or : logos, affiches, tickets et animations. L’événement a eu lieu le 16 décembre 2025 à l’IUT de Lens. L’objectif était de créer une identité visuelle mettant en avant nos valeurs, celles du cinéma et capable de représenter la diversité des projets et de donner une cohérence graphique à l’ensemble de la communication.",
    "tags": [""],
    "featured": true,
    "media": [
      "images/projects/MMIDOR/affiche_claire.png",
      "images/projects/MMIDOR/logo_carré.png",
      "images/projects/MMIDOR/logo_long.png",
      "https://res.cloudinary.com/djgl3a7kw/video/upload/v1768938873/annonce_fzdq6n.mp4",
      "https://res.cloudinary.com/djgl3a7kw/video/upload/v1768938353/d_une_main_%C3%A0_l_autre_1_rjdaai.mp4",
      "https://res.cloudinary.com/djgl3a7kw/video/upload/v1768938874/logo_motion_n2guae.mp4",
      "https://res.cloudinary.com/djgl3a7kw/video/upload/v1768938875/universal_vibe_kgjp2z.mp4"
    ],
    "outils": ["Photoshop", "Illustrator", "After Effects", "Premiere Pro"],
    "category": "BUT2"
  },
  {
    "id": 4,
    "slug": "starbolt",
    "title": "STARBOLT",
    "type": "Marque",
    "year": 2025,
    "cover": "images/projects/starbolt/affiche.jpg",
    "description": "Rebranding fictif de Starbucks avec la création d’une gamme de boissons énergisantes appelée StarBolt. Chaque produit a un goût unique, avec une attention particulière portée à la Rainbow StarBolt, symbole de la diversité et du mois de juin (Pride). Le projet explore le marketing expérimental, en associant une marque existante à une identité visuelle jeune, dynamique et colorée.",
    "tags": ["Affiche", "Marque", "Logo", "Mockup"],
    "featured": true,
    "media": [
      "images/projects/starbolt/logo_bleu.png",
      "images/projects/starbolt/bleu_or.png",
      "images/projects/starbolt/logo_noir.png",
      "images/projects/starbolt/noir_rose.png",
      "images/projects/starbolt/logo_rouge.png",
      "images/projects/starbolt/orange_rouge.png",
      "images/projects/starbolt/logo_rainbow.png",
      "images/projects/starbolt/rainbow.png",
      "images/projects/starbolt/logo_jaune.png",
      "images/projects/starbolt/rouge_or.png",
      "images/projects/starbolt/logo_vert.png",
      "images/projects/starbolt/vert_argent.png",
      "images/projects/starbolt/logo_violet.png",
      "images/projects/starbolt/violet_bleu.png"
    ],
    "outils": ["Photoshop" , "Illustrator"],
    "category": "BUT1"
  },
  {
    "id": 5,
    "slug": "gala",
    "title": "Gala de danse classique 2025",
    "type": "Évènement",
    "year": 2025,
    "cover": "images/projects/gala/gala10.jpg",
    "description": "Série photographique réalisée en tant que bénévole lors du gala 2025 de l’école de danse classique Éliane Fiévé. Les images capturent la grâce et la technique des danseuses, ainsi que l’atmosphère féerique et festive de l’événement. Chaque photo met en valeur le mouvement, la lumière et la composition pour raconter l’histoire du gala.",
    "tags": ["Photo"],
    "featured": true,
    "media": [
      "images/projects/gala/gala1.jpg",
      "images/projects/gala/gala7.jpg",
      "images/projects/gala/gala2.jpg",
      "images/projects/gala/gala8.jpg",
      "images/projects/gala/gala3.jpg",
      "images/projects/gala/gala9.jpg",
      "images/projects/gala/gala4.jpg",
      "images/projects/gala/gala5.jpg",
      "images/projects/gala/gala6.jpg",
      "images/projects/gala/gala10.jpg"
    ],
    "outils": ["Lightroom", "Canon EOS R50"],
    "category": "Perso"
  },
  {
    "id": 6,
    "slug": "fete-de-la-citrouille",
    "title": "Fête de la Citrouille 2025",
    "type": "Évènement",
    "year": 2025,
    "cover": "images/projects/citrouille/10.jpg",
    "description": "Photographies prises lors de la fête de la citrouille 2025 à Marquillies, en tant que bénévole. Les clichés illustrent l’ambiance chaleureuse et conviviale de l’événement, les activités et la participation des habitants. Une approche visuelle qui met l’accent sur la couleur, la fête et la convivialité, tout en restant spontanée et naturelle.",
    "tags": ["Photo"],
    "featured": true,
    "media": [
      "images/projects/citrouille/1.jpg",
      "images/projects/citrouille/2.jpg",
      "images/projects/citrouille/3.jpg",
      "images/projects/citrouille/4.jpg",
      "images/projects/citrouille/5.jpg",
      "images/projects/citrouille/6.jpg",
      "images/projects/citrouille/7.jpg",
      "images/projects/citrouille/8.jpg",
      "images/projects/citrouille/9.jpg",
      "images/projects/citrouille/10.jpg",
      "images/projects/citrouille/11.jpg",
      "images/projects/citrouille/12.jpg",
      "images/projects/citrouille/13.jpg",
      "images/projects/citrouille/14.jpg",
      "images/projects/citrouille/15.jpg"
    ],
    "outils": ["Lightroom", "Canon EOS R50"],
    "category": "Perso"
  },
  {
    "id": 7,
    "slug": "bleach",
    "title": "Concert de Bleach",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/bleach.jpg",
    "description": "Affiche publicitaire créée pour le concert du groupe de rock Bleach, à l’occasion de la Fête de la Musique. Le design met en avant l’énergie et le dynamisme du groupe, avec des éléments graphiques audacieux pour attirer l’attention du public et refléter l’ambiance du concert.",
    "tags": ["Affiche", "Musique", "Publicité"],
    "featured": true,
    "outils": ["Photoshop"],
    "category": "Perso"
  },
  {
    "id": 8,
    "slug": "laylow",
    "title": "Laylow - Trinity",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/laylow.jpg",
    "description": "Affiche digitale pour l’album Trinity du chanteur Laylow. Le projet reprend l’univers visuel de l’album avec des codes graphiques numériques et des couleurs vertes caractéristiques. L’objectif était de créer une communication visuelle cohérente avec le style musical et l’identité de l’artiste.",
    "tags": ["Affiche", "Musique"],
    "featured": true,
    "outils": ["Photoshop"],
    "category": "Perso"
  },
  {
    "id": 9,
    "slug": "pnl",
    "title": "Minto x PNL",
    "type": "Marque",
    "year": 2025,
    "cover": "images/projects/pnl.jpg",
    "description": "Création d’une marque de chewing-gum fictive, Minto, en collaboration avec le duo PNL. Le projet consistait à imaginer un goût inédit : cassis-pêche, reflétant l’univers sombre et lunaire (cassis) de leur album Deux Frères ainsi que la dimension solaire (pêche) de leur album Dans la Légende. Le slogan fait référence à leur phrase “Deux frères, deux fauves”, créant un lien fort entre produit et storytelling.",
    "tags": ["Affiche", "Marque", "Publicité"],
    "featured": true,
    "outils": ["Photoshop", "Illustrator"],
    "category": "BUT2"
  },
  {
    "id": 10,
    "slug": "luther",
    "title": "Luther - Aled",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/luther.jpg",
    "description": "Affiche de l’album Exit du rappeur Luther, utilisant un univers bleu et rose. L’objectif était de traduire visuellement l’atmosphère de l’album, en jouant sur les contrastes, les textures et la typographie pour transmettre une identité musicale forte et moderne.",
    "tags": ["Affiche", "Musique"],
    "featured": true,
    "outils": ["Photoshop"],
    "category": "Perso"
  },
  {
    "id": 11,
    "slug": "von-dutch",
    "title": "Von Dutch",
    "type": "Graphisme",
    "year": 2025,
    "cover": "images/projects/vondutch_recto.jpg",
    "description": "Conception d’un dépliant 3 plis fictif pour la collection Peace & Freedom de la marque Von Dutch. Le projet consistait à réunir 10 articles, avec toutes les informations nécessaires (adresses, descriptions, visuels). La direction artistique a été pensée pour créer un support clair, structuré et attractif, cohérent avec l’identité de la marque.",
    "tags": ["Dépliant", "Publicité"],
    "featured": true,
    "media": [
      "images/projects/vondutch_verso.jpg"
    ],
    "outils": ["InDesign", "Photoshop", "ProCreate"],
    "category": "BUT2"
  },
  {
    "id": 12,
    "slug": "make-it-pop",
    "title": "Festival Make It Pop",
    "type": "Évènement",
    "year": 2025,
    "cover": "images/projects/MIP/affiche.jpg",
    "description": "Direction artistique complète d’un festival fictif sur le thème du hip-hop et du street-art. Création d’affiches, flyers, bannières et merchandising. Le projet reprend les codes vintage du hip-hop et les bases du street-art, pour offrir une identité visuelle forte et immersive, capable de séduire un public jeune et dynamique.",
    "tags": ["Affiche", "Bannière", "Flyer", "Mockup"],
    "featured": true,
    "media": [
      "images/projects/MIP/affiche.jpg",
      "images/projects/MIP/bannière.png",
      "images/projects/MIP/flyer_recto.jpg",
      "images/projects/MIP/flyer_verso.png",
      "images/projects/MIP/jersey.png"
    ],
    "outils": ["Photoshop", "Illustrator"],
    "category": "BUT1"
  },
  {
    "id": 13,
    "slug": "ptites-pages",
    "title": "Les ptites pages",
    "type": "Marque",
    "year": 2025,
    "cover": "images/projects/ptitespages/mockup_malynx.jpg",
    "description": "Réalisation de la direction artistique pour une maison d’édition fictive destinée aux enfants. Conception des personnages et des couvertures de livres/magazines. L’objectif était de créer un univers ludique, coloré et reconnaissable, permettant aux jeunes lecteurs de s’immerger dans les histoires et d’identifier facilement la marque éditoriale.",
    "tags": ["Produit", "Marque", "Mockup"],
    "featured": true,
    "media": [
      "images/projects/ptitespages/boubou.png",
      "images/projects/ptitespages/loulou.png",
      "images/projects/ptitespages/porcetpic.png",
      "images/projects/ptitespages/raphael.png",
      "images/projects/ptitespages/MagazineMockup1.jpg",
      "images/projects/ptitespages/MagazineMockup2.jpg",
      "images/projects/ptitespages/MagazineMockup3.jpg",
      "images/projects/ptitespages/mockup_boubou.jpg",
      "images/projects/ptitespages/mockup_malynx.jpg"
    ],
    "outils": ["Photoshop", "Illustrator"],
    "category": "BUT1"
  }
]
